<template>
  <section class="card">
    <h2>{{ $t('sections.filter') }}</h2>

    <div class="field">
      <label>{{ $t('fields.exclude_filenames.label') }}</label>

      <!-- Tag-Chips -->
      <div class="tags-container" @click="focusInput">
        <span
          v-for="(tag, index) in tags"
          :key="index"
          class="tag"
        >
          {{ tag }}
          <button type="button" class="tag-remove" @click.stop="removeTag(index)">×</button>
        </span>
        <input
          ref="tagInput"
          v-model="inputValue"
          type="text"
          class="tag-input"
          placeholder="Add filter pattern… (Enter or , to confirm)"
          @keydown.enter.prevent="addTag"
          @keydown.comma.prevent="addTag"
          @keydown.backspace="onBackspace"
        />
      </div>

      <p class="hint">{{ $t('fields.exclude_filenames.hint') }}</p>

      <!-- Beispielblock -->
      <div class="filter-examples">
        <p class="examples-title">Supported formats &amp; examples:</p>

        <div class="example-block">
          <span class="example-type">Exact filename</span>
          <code>IMG_20231224_Christmas.jpg</code>
          <span class="example-desc">Excludes exactly this one file.</span>
        </div>

        <div class="example-block">
          <span class="example-type">Wildcard (extension)</span>
          <code>*.svg</code>
          <code>*.bmp</code>
          <code>*.tiff</code>
          <span class="example-desc">Excludes all files with that extension. Useful to block unsupported formats.</span>
        </div>

        <div class="example-block">
          <span class="example-type">Regex – legacy video</span>
          <code>/\.(avi|wmv|flv|rm|rmvb|3gp|asf|vob)$/i</code>
          <span class="example-desc">Excludes formats browsers cannot play: AVI, WMV, Flash Video, RealMedia, 3GP, ASF, DVD-VOB.</span>
        </div>

        <div class="example-block">
          <span class="example-type">Regex – HDR duplicates</span>
          <code>/^IMG_\d{8}_\d{6}_HDR/</code>
          <span class="example-desc">Skips HDR duplicate files generated by Android cameras (e.g. IMG_20240615_143022_HDR.jpg).</span>
        </div>

        <div class="example-block">
          <span class="example-type">Regex – thumbnails</span>
          <code>/thumbnail|thumb|_small\./i</code>
          <span class="example-desc">Skips auto-generated thumbnail variants in the same folder.</span>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed } from 'vue'

const props = defineProps(['modelValue'])
const emit  = defineEmits(['update:modelValue'])

const inputValue = ref('')
const tagInput   = ref(null)

const tags = computed(() =>
  Array.isArray(props.modelValue.exclude_filenames)
    ? props.modelValue.exclude_filenames
    : []
)

function focusInput() { tagInput.value?.focus() }

function addTag() {
  const val = inputValue.value.trim().replace(/,$/, '').trim()
  if (val && !tags.value.includes(val)) {
    emit('update:modelValue', {
      ...props.modelValue,
      exclude_filenames: [...tags.value, val]
    })
  }
  inputValue.value = ''
}

function removeTag(index) {
  emit('update:modelValue', {
    ...props.modelValue,
    exclude_filenames: tags.value.filter((_, i) => i !== index)
  })
}

function onBackspace() {
  if (inputValue.value === '' && tags.value.length > 0) {
    removeTag(tags.value.length - 1)
  }
}
</script>

<style scoped>
.card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 1.5rem;
  margin-bottom: 1.5rem;
}

h2 {
  font-size: 0.82rem;
  color: var(--accent);
  margin-bottom: 1.2rem;
  text-transform: uppercase;
  letter-spacing: 0.07em;
  font-weight: 700;
}

.field { margin-bottom: 1rem; }

label {
  display: block;
  font-size: 0.82rem;
  color: var(--text-muted);
  margin-bottom: 0.3rem;
}

.hint {
  font-size: 0.75rem;
  color: var(--text-muted);
  margin-top: 0.25rem;
  line-height: 1.4;
  opacity: 0.7;
}

/* Tag-Input */
.tags-container {
  display: flex;
  flex-wrap: wrap;
  gap: 0.4rem;
  align-items: center;
  min-height: 2.5rem;
  background: var(--input-bg);
  border: 1px solid var(--input-border);
  border-radius: 6px;
  padding: 0.4rem 0.6rem;
  cursor: text;
  transition: border-color 0.15s;
}
.tags-container:focus-within { border-color: var(--input-focus); }

.tag {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  background: color-mix(in srgb, var(--accent) 18%, transparent);
  color: var(--accent);
  border: 1px solid color-mix(in srgb, var(--accent) 35%, transparent);
  border-radius: 4px;
  padding: 0.15rem 0.5rem;
  font-size: 0.82rem;
  white-space: nowrap;
  font-family: monospace;
}

.tag-remove {
  background: none;
  border: none;
  color: var(--accent);
  cursor: pointer;
  font-size: 1rem;
  line-height: 1;
  padding: 0;
  opacity: 0.7;
  transition: opacity 0.15s;
}
.tag-remove:hover { opacity: 1; }

.tag-input {
  flex: 1;
  min-width: 160px;
  background: transparent;
  border: none;
  outline: none;
  color: var(--text);
  font-size: 0.9rem;
  font-family: monospace;
  padding: 0.1rem 0.2rem;
}
.tag-input::placeholder { color: var(--text-muted); opacity: 0.5; }

/* Beispielblock */
.filter-examples {
  margin-top: 0.8rem;
  padding: 0.85rem 1rem;
  background: var(--input-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  font-size: 0.78rem;
}

.examples-title {
  color: var(--text-muted);
  font-weight: 600;
  margin-bottom: 0.65rem;
  text-transform: uppercase;
  font-size: 0.72rem;
  letter-spacing: 0.05em;
}

.example-block {
  display: flex;
  flex-wrap: wrap;
  align-items: baseline;
  gap: 0.35rem 0.5rem;
  margin-bottom: 0.55rem;
  line-height: 1.5;
}
.example-block:last-child { margin-bottom: 0; }

.example-type {
  font-weight: 700;
  color: var(--accent);
  min-width: 145px;
  font-size: 0.74rem;
  flex-shrink: 0;
}

.example-block code {
  background: var(--card-bg);
  color: var(--accent-light);
  padding: 0.1em 0.45em;
  border-radius: 4px;
  font-family: monospace;
  font-size: 0.76rem;
  border: 1px solid var(--border);
  white-space: nowrap;
}

.example-desc {
  color: var(--text-muted);
  font-size: 0.74rem;
  line-height: 1.4;
}
</style>
